#https://api-platform.com/docs/core/configuration/
api_platform:
    title: 'KDN OZG API'

    # The description of the API.
    description: 'OZG NRW kommunal – Onlinedienste zum Onlinezugangsgesetz'

    # The version of the API.
    version: '0.1.0'
    mapping:
        #paths: ['%kernel.project_dir%/src/Entity']
        paths: ['%kernel.project_dir%/config/api_platform/resources']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
