parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(DATABASE_URL): ''
  env(DATABASE_URL_CMS): ''

doctrine:
  dbal:
    connections:
      default:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '%env(resolve:DATABASE_VERSION)%'
        charset: utf8mb4
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
      cms:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '%env(resolve:DATABASE_VERSION)%'
        charset: utf8
        default_table_options:
          charset: utf8
          collate: utf8_general_ci
        url: '%env(resolve:DATABASE_URL_CMS)%'
    types:
      datetime: App\Types\UTCDateTimeType
  orm:
    auto_generate_proxy_classes: true
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
          datetime_functions:
            FROM_UNIXTIME: DoctrineExtensions\Query\Mysql\FromUnixtime
            WEEKDAY: DoctrineExtensions\Query\Mysql\WeekDay
            YEAR: DoctrineExtensions\Query\Mysql\Year
            DATE: DoctrineExtensions\Query\Mysql\Date
          string_functions:
            REPLACE: DoctrineExtensions\Query\Mysql\Replace
        filters:
          softdeleteable:
            class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
            enabled: true
        mappings:
          SonataUserBundle: null
          App:
            is_bundle: false
            type: annotation
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: App
      cms:
        connection: cms
    resolve_target_entities:
      Symfony\Component\Security\Core\User\UserInterface: App\Entity\User

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
