simple_things_entity_audit:
  audited_entities:
    - App\Entity\Onboarding\CommuneInfo
    - App\Entity\Onboarding\Contact
    - App\Entity\Onboarding\Epayment
    - App\Entity\Onboarding\EpaymentProject
    - App\Entity\Onboarding\EpaymentService
    - App\Entity\Onboarding\FormSolution
    - App\Entity\Onboarding\Release
    - App\Entity\Onboarding\ServiceAccount
    - App\Entity\Onboarding\MonumentAuthority
    - App\Entity\Onboarding\XtaServer
    - App\Entity\Onboarding\OnboardingDocument
    - App\Entity\ModelRegion\ModelRegionProject
    - App\Entity\StateGroup\Commune
    - App\Entity\StateGroup\ServiceProvider
    - App\Entity\ImplementationProject
    - App\Entity\Solution
    - App\Entity\SpecializedProcedure
    - App\Entity\Service
    - App\Entity\ServiceSystem
  global_ignore_columns:
    - createdAt
    - modifiedAt
    - modifiedBy
    - lastLogin