# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                locator: filesystem
                data_root:
                    #- '%kernel.project_dir%/secured-data'
                    - '%kernel.project_dir%/public'

    #http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html#the-relative-resize-filter
    filter_sets:
        default_small:
            quality: 85
            filters:
                thumbnail: { size: [100, 100], mode: inset }

        default_big:
            quality: 85
            filters:
                thumbnail: { size: [800, 800], mode: inset }

        default_content_image:
            quality: 85
            filters:
                thumbnail: { size: [500, 700], mode: inset }

        default_image_aside:
            quality: 85
            filters:
                thumbnail: { size: [393, 1000], mode: inset }

        # the name of the "filter set"
        default_image_xxl:
            quality: 85
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [1000, 1000], mode: inset }
