# https://sonata-project.org/bundles/admin/3-x/doc/reference/dashboard.html
sonata_admin:
    title_logo: 'template/logo.svg'
    title: KDN - DWH
    show_mosaic_button: false
    security:
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    templates:
        show: 'General/Show/show.html.twig'
    options:
        legacy_twig_text_extension: false
        use_icheck: false # disable iCheck
    assets:
#        javascripts:
#            - bundles/sonatacore/vendor/jquery/dist/jquery.min.js
#            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
#            - bundles/sonatacore/vendor/moment/min/moment.min.js
#            - bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js
#            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
#            - bundles/sonataadmin/vendor/jquery-form/jquery.form.js
#            - bundles/sonataadmin/jquery/jquery.confirmExit.js
#            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
#            - bundles/sonatacore/vendor/select2/select2.min.js
#            - bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js
#            - bundles/sonataadmin/vendor/iCheck/icheck.min.js
#            - bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js
#            - bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js
#            - bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js
#            - bundles/sonataadmin/vendor/readmore-js/readmore.min.js
#            - bundles/sonataadmin/vendor/masonry/dist/masonry.pkgd.min.js
#            - bundles/sonataadmin/Admin.js
#            - bundles/sonataadmin/treeview.js
#            - bundles/sonataadmin/sidebar.js
#            - bundles/sonatacore/js/base.js
        extra_javascripts:
            - bundles/fosckeditor/ckeditor.js
            - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
            - bundles/sonataformatter/markitup/sets/markdown/set.js
            - bundles/sonataformatter/markitup/sets/html/set.js
            - bundles/sonataformatter/markitup/sets/textile/set.js
        extra_stylesheets:
            - bundles/sonataformatter/markitup/skins/sonata/style.css
            - bundles/sonataformatter/markitup/sets/markdown/style.css
            - bundles/sonataformatter/markitup/sets/html/style.css
            - bundles/sonataformatter/markitup/sets/textile/style.css
    dashboard:
        blocks:
            -
                position: top
                type: App\Block\RecentSolutionsBlock
                class: 'col-xs-12 col-lg-8'
                settings:
                    title: 'app.solution.recent_solutions'
                    translation_domain: 'messages'
                    mode: 'admin'
                    code:  App\Admin\SolutionAdmin
            -
                position: top
                type: App\Block\RecentActivitiesBlock
                class: 'col-xs-12 col-lg-4'
                settings:
                    title: 'app.common.recent_activities.block_title'
                    translation_domain: 'messages'
                    mode: 'admin'
            -
                class:    clear-left-md col-xs-12 col-sm-6 col-lg-4
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  App\Admin\Frontend\ServiceSystemAdmin    # admin code - service id
                    icon:  fa-tasks                  # font awesome icon
                    text:  app.block.service_system.total
                    color: bg-green                 # colors: bg-green, bg-red and bg-aqua
                    #filters:                         # filter values
                    #    status: { value: 4 }
            -
                class:    col-xs-12 col-sm-6 col-lg-4
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  App\Admin\Frontend\ServiceSystemAdmin    # admin code - service id
                    icon:  fa-tasks                  # font awesome icon
                    text:  app.block.service_system.communal_execution
                    color: bg-green                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        jurisdictions: { value:  [3] }
            -
                class:    col-xs-12 col-sm-6 col-lg-4
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  App\Admin\ImplementationProjectAdmin    # admin code - service id
                    icon:  fa-wrench                  # font awesome icon
                    text:  app.block.implementation_project.total
                    color: bg-green                 # colors: bg-green, bg-red and bg-aqua
                    #filters:                         # filter values
                    #    status: { value: 4 }
            -
                position: top
                type: App\Block\StatisticsBlock
                class: 'col-xs-12 col-lg-6'
                settings:
                    title: 'app.statistics.solution_maturity'
                    translation_domain: 'messages'
                    mode: 'admin'
                    provider: App\Statistics\Provider\SolutionMaturityChartProvider
            -
                position: top
                type: App\Block\StatisticsBlock
                class: 'col-xs-12 col-lg-6'
                settings:
                    title: 'app.statistics.solution_status'
                    translation_domain: 'messages'
                    mode: 'admin'
                    provider: App\Statistics\Provider\SolutionStatusChartProvider
            -
                position: top
                type: App\Block\StatisticsBlock
                class: 'col-xs-12 col-lg-6'
                settings:
                    title: 'app.statistics.implementation_project_status'
                    translation_domain: 'messages'
                    mode: 'admin'
                    provider: App\Statistics\Provider\ImplementationProjectStatusChartProvider

            - { position: left,  type: sonata.admin.block.admin_list, settings: { groups: [app.ozg_implementation_group, app.settings_group, app.state_group, app.onboarding_group] } }
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [app.implementation_group, app.digital_model_reqion_group, app.application_group, app.efile_group, app_admin.menu.system] } }
            -
                class:    col-xs-6 col-lg-3
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  App\Admin\SolutionAdmin    # admin code - service id
                    icon:  fa-lightbulb-o                  # font awesome icon
                    text:  app.block.solution.online            # static text or translation message
                    color: bg-green                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        status: { value: 4 }
            -
                class:    col-xs-6 col-lg-3
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  App\Admin\SolutionAdmin    # admin code - service id
                    icon:  fa-lightbulb-o                  # font awesome icon
                    text:  app.block.solution.partially_online            # static text or translation message
                    color: bg-yellow                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        status: { value: 5 }
            -
                class:    col-xs-6 col-lg-3
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  App\Admin\SolutionAdmin    # admin code - service id
                    icon:  fa-lightbulb-o                  # font awesome icon
                    text:  app.block.solution.offline            # static text or translation message
                    color: bg-red                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        status: { value: 1 }
            -
                class:    col-xs-6 col-lg-3
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  App\Admin\SolutionAdmin    # admin code - service id
                    icon:  fa-lightbulb-o                  # font awesome icon
                    text:  app.block.solution.maturity_4
                    color: bg-green                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        maturity: { value:  [5] } # Maturity ID 5 => Label: '4'

        groups:
            app.ozg_implementation_group:
                label: app.menu.ozg_implementation_group
                label_catalogue: messages
                icon: '<i class="fa fa-building"></i>'
                items:
                    - App\Admin\SolutionAdmin
                    - App\Admin\ImplementationProjectAdmin
            app.settings_group:
                label: app.menu.settings_group
                label_catalogue: messages
                icon: '<i class="fa fa-wrench"></i>'
                items:
                    - App\Admin\SubjectAdmin
                    - App\Admin\SituationAdmin
                    - App\Admin\ServiceSystemAdmin
                    - App\Admin\ServiceAdmin
            app.state_group:
                label: app.menu.state_group
                label_catalogue: messages
                icon: '<i class="fa fa-building"></i>'
                items:
                    - App\Admin\StateGroup\CommuneAdmin
                    - App\Admin\StateGroup\ServiceProviderAdmin
                    - App\Admin\StateGroup\MinistryStateAdmin
                    - App\Admin\StateGroup\CentralAssociationAdmin
                    - App\Admin\StateGroup\BureauAdmin
                    - App\Admin\StateGroup\AdministrativeDistrictAdmin
                    #- App\Admin\CommuneServiceAdmin
                    #- App\Admin\ServiceSolutionAdmin
            app.implementation_group:
                label: app.menu.implementation_group
                label_catalogue: messages
                icon: '<i class="fa fa-object-group"></i>'
                items:
                    - App\Admin\MaturityAdmin
                    - App\Admin\StatusAdmin
                    - App\Admin\PortalAdmin
                    - App\Admin\LaboratoryAdmin
                    - App\Admin\SpecializedProcedureAdmin
                    - App\Admin\ManufacturerAdmin
                    - App\Admin\FormServerAdmin
                    - App\Admin\PriorityAdmin
                    - App\Admin\ImplementationStatusAdmin
                    - App\Admin\ContactAdmin
                    - App\Admin\CategoryAdmin
                    - App\Admin\MailingAdmin
                    - App\Admin\OrganisationAdmin
                    - App\Admin\FundingAdmin
                    #- App\Admin\JurisdictionAdmin
            app.digital_model_reqion_group:
                label: app.menu.digital_model_reqion_group
                label_catalogue: messages
                icon: '<i class="fa fa-object-group"></i>'
                items:
                    - App\Admin\ModelRegionAdmin
                    - App\Admin\ModelRegionProjectAdmin
                    - App\Admin\ModelRegionBeneficiaryAdmin
            app.application_group:
                label: app.menu.application_group
                label_catalogue: messages
                icon: '<i class="fa fa-object-group"></i>'
                items:
                    - App\Admin\ApplicationAdmin
                    - App\Admin\ApplicationCategoryAdmin
            app.efile_group:
                label: app.menu.efile_group
                label_catalogue: messages
                icon: '<i class="fa fa-object-group"></i>'
                items:
                    - App\Admin\EFileAdmin
                    - App\Admin\EFileStatusAdmin
                    - App\Admin\EFileStorageTypeAdmin
            app.onboarding_group:
                label: app.menu.onboarding_group
                label_catalogue: messages
                icon: '<i class="fa fa-ship"></i>'
                items:
                    - App\Admin\Onboarding\CommuneInfoAdmin
                    - App\Admin\Onboarding\EpaymentAdmin
                    - App\Admin\Onboarding\ServiceAccountAdmin
                    - App\Admin\Onboarding\DataclearingAdmin
                    - App\Admin\Onboarding\InquiryAdmin
                    - App\Admin\Onboarding\OnboardingServiceAdmin
            app_admin.menu.basic:
                label: app.menu.basic_group
                label_catalogue: messages
                icon: '<i class="fa fa-object-group"></i>'
                items:
                    - App\Admin\PaymentTypeAdmin
                    - App\Admin\AuthenticationAdmin
                    - App\Admin\AnalogServiceAdmin
                    - App\Admin\OpenDataAdmin
                    - App\Admin\StateGroup\CommuneTypeAdmin
                    - App\Admin\PageContentAdmin
            app_admin.menu.system:
                label: app.system_group
                #label_catalogue: messages
                label_catalogue: SonataAdminBundle
                icon: '<i class="fa fa-cog"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - App\Admin\Api\ApiConsumerAdmin
                    - App\Admin\MetaData\MetaItemAdmin
                    - App\Admin\Configuration\CustomFieldAdmin
                    - App\Admin\Configuration\EmailTemplateAdmin
                    #- shapecode_cron.cronjob
                    #- shapecode_cron.cronjob_result

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        App\Block\RecentSolutionsBlock:
            contexts: [admin]
        App\Block\StatisticsBlock:
            contexts: [admin]