app_frontend_global_search:
  path: /search
  controller: App\Action\SearchAction

frontend_app_modelregionproject_list:
  path: /dmr-umsetzungsprojekte
  controller: App\Controller\ModelRegion\ModelRegionProjectController::listAction

frontend_app_modelregionproject_show_default:
  path: /dmr-umsetzungsprojekte/{id}/show
  controller: App\Controller\ModelRegion\ModelRegionProjectController::showAction

frontend_app_modelregionproject_show:
  path: /dmr-umsetzungsprojekte/details/{slug}
  controller: App\Controller\ModelRegion\ModelRegionProjectController::showBySlugAction

frontend_app_modelregionproject_export:
  path: /dmr-umsetzungsprojekte/export
  controller: App\Controller\ModelRegion\ModelRegionProjectController::exportAction

frontend_app_modelregionproject_download:
  path: /dmr-umsetzungsprojekte/{id}/download/{documentId}
  controller: App\Controller\ModelRegion\ModelRegionProjectController::downloadAction

frontend_app_modelregionproject_export_concept_pdf:
  path: /dmr-umsetzungsprojekte/konzeptabfrage/{id}/pdf
  controller: App\Controller\ModelRegion\ModelRegionProjectController::exportPdfConceptAction

frontend_app_modelregion_list:
  path: /modellregionen
  controller: App\Controller\ModelRegionController::listAction

frontend_app_modelregion_show_default:
  path: /modellregionen/{id}/show
  controller: App\Controller\ModelRegionController::showAction

frontend_app_modelregion_show:
  path: /modellregionen/details/{slug}
  controller: App\Controller\ModelRegionController::showBySlugAction

frontend_app_modelregion_export:
  path: /modellregionen/export
  controller: App\Controller\ModelRegionController::exportAction

