# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\StateGroup\CommuneType:
  #shortName: 'Leika-Leistungen'
  ##description: 'Größenklasse der Kommunen'
  attributes:
    pagination_items_per_page: 25

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'commune_type:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit OZG Größenklasse der Kommunen zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'commune_type:read']
      openapiContext:
        description: 'Gibt eine OZG Größenklasse der Kommunen zurück'