# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\StateGroup\CommuneType:
  #shortName: 'Leika-Leistungen'
  ##description: 'Größenklasse der Kommunen'
  attributes:
    pagination_items_per_page: 25

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalization_context:
        enable_max_depth: 1
        groups: ['collection:read', 'commune_type:collection:read']
      openapi_context:
        summary: 'Gibt eine Liste mit OZG Größenklasse der Kommunen zurück'
  #    post:
  #      security: 'is_granted("ROLE_ADMIN")'

    ApiPlatform\Metadata\Get:
      normalization_context:
        enable_max_depth: 1
        groups: ['item:read', 'commune_type:read']
      openapi_context:
        summary: 'Gibt eine OZG Größenklasse der Kommunen zurück'
  #    put:
  #      method: 'PUT'