App\Entity\Onboarding\CommuneInfo:
  attributes:
    security: 'is_granted("PERMISSION_API_ONBOARDING")'
    pagination_items_per_page: 25
  description: 'Kommunalportal Basisdaten'

  collectionOperations:
    get:
      method: 'GET'
      normalization_context:
        enable_max_depth: 1
        groups: ['collection:read', 'commune_info:collection:read']
      openapi_context:
        summary: 'Gibt eine Liste mit Kommunalportal Basisdaten zurück'

  itemOperations:
    get:
      method: 'GET'
      normalization_context:
        enable_max_depth: 1
        groups: ['item:read', 'commune_info:read']
      openapi_context:
        summary: 'Gibt einen Eintrag der Kommunalportal Basisdaten zurück'