App\Entity\Onboarding\CommuneInfo:
  #security: 'is_granted("PERMISSION_API_ONBOARDING")'
  attributes:
    pagination_items_per_page: 25
  #description: 'Kommunalportal Basisdaten'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'commune_info:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Kommunalportal Basisdaten zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'commune_info:read']
      openapiContext:
        description: 'Gibt einen Eintrag der Kommunalportal Basisdaten zurück'