# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\StateGroup\Commune:
  #routePrefix: /library
  #shortName: 'Leika-Leistungen'
  ##description: 'Kommunen'
  attributes:
    pagination_items_per_page: 25

  operations:
    ApiPlatform\Metadata\GetCollection:
#      uriTemplate: '/grimoire'
#      status: 301
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'commune:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Kommunen zurück'
      filters: ['App\Api\ApiPlatform\Filter\FulltextSearchFilter']
    #    post:
    #      #security: 'is_granted("ROLE_ADMIN")'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'commune:read']
      openapiContext:
        description: 'Gibt eine Kommune zurück'
    #    put:
    #      method: 'PUT'
    # api/config/api_platform/resources.yaml

#      uriTemplate: '/grimoire/{id}'
#      requirements:
#        id: '\d+'
#      defaults:
#        color: 'brown'
#      host: '{subdomain}.api-platform.com'
#      schemes: [ 'https' ]
#      options:
#        my_option: 'my_option_value'