App\Entity\Onboarding\Contact:
  #security: 'is_granted("PERMISSION_API_ONBOARDING")'
  attributes:
    pagination_items_per_page: 25
  ##description: 'Kommunalportal Kontakte'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'onboarding_contact:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Kommunalportal Kontakte zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'onboarding_contact:read']
      openapiContext:
        description: 'Gibt einen Eintrag der Kommunalportal Kontakte zurück'