App\Entity\Onboarding\EpaymentProject:
  #security: 'is_granted("PERMISSION_API_ONBOARDING")'
  attributes:
    pagination_items_per_page: 25
  ##description: 'Kommunalportal ePayment Projekte'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'epayment_project:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Kommunalportal ePayment Projekte zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'epayment_project:read']
      openapiContext:
        description: 'Gibt einen Eintrag der Kommunalportal ePayment Projekte zurück'