App\Entity\Onboarding\Epayment:
  #security: 'is_granted("PERMISSION_API_ONBOARDING")'
  attributes:
    pagination_items_per_page: 25
  ##description: 'Kommunalportal ePayment'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'epayment:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Kommunalportal ePayment zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'epayment:read']
      openapiContext:
        description: 'Gibt einen Eintrag der Kommunalportal ePayment zurück'