App\Entity\Onboarding\FormSolution:
  #security: 'is_granted("PERMISSION_API_ONBOARDING")'
  attributes:
    pagination_items_per_page: 25
  ##description: 'Kommunalportal Formsolutions'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'form_solution:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Kommunalportal Formsolutions zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'form_solution:read']
      openapiContext:
        description: 'Gibt einen Eintrag der Kommunalportal Formsolutions zurück'