# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\ImplementationProject:
  #shortName: 'Leika-Leistungen'
  ##description: 'Umsetzungsprojekte'
  attributes:
    pagination_items_per_page: 25

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'implementation_project:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit OZG Umsetzungsprojekten zurück'
      filters: ['App\Api\ApiPlatform\Filter\FulltextSearchFilter']

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'implementation_project:read']
      #\ApiPlatform\OpenApi\Factory\OpenApiFactory::collectPaths
      openapiContext:
        description: 'Gibt ein OZG Umsetzungsprojekt zurück'