App\Entity\Onboarding\Inquiry:
  #security: 'is_granted("PERMISSION_API_ONBOARDING")'
  attributes:
    pagination_items_per_page: 25
  ##description: 'Kommunalportal Rückfragen'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'inquiry:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Kommunalportal Rückfragen zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'inquiry:read']
      openapiContext:
        description: 'Gibt einen Eintrag der Kommunalportal Rückfragen zurück'