# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\ModelRegion\ModelRegionProject:
  #shortName: 'Leika-Leistungen'
  ##description: 'DMR Umsetzungsprojekte'
  attributes:
    pagination_items_per_page: 25

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'model_region_project:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit DMR Umsetzungsprojekten zurück'
      filters: ['App\Api\ApiPlatform\Filter\FulltextSearchFilter']

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'model_region_project:read']
      openapiContext:
        description: 'Gibt ein DMR Umsetzungsprojekt zurück'