# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\ModelRegion\ModelRegion:
  #shortName: 'Leika-Leistungen'
  ##description: 'Modellregionen'
  attributes:
    pagination_items_per_page: 25

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalization_context:
        enable_max_depth: 1
        groups: ['collection:read', 'model_region:collection:read']
      openapi_context:
        summary: 'Gibt eine Liste mit OZG Modellregionen zurück'
      filters: ['App\Api\ApiPlatform\Filter\FulltextSearchFilter']
  #    post:
  #      security: 'is_granted("ROLE_ADMIN")'

    ApiPlatform\Metadata\Get:
      normalization_context:
        enable_max_depth: 1
        groups: ['item:read', 'model_region:read']
      openapi_context:
        summary: 'Gibt eine OZG Modellregion zurück'
  #    put:
  #      method: 'PUT'