# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\ModelRegion\ModelRegion:
  #shortName: 'Leika-Leistungen'
  ##description: 'Modellregionen'
  attributes:
    pagination_items_per_page: 25

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'model_region:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit OZG Modellregionen zurück'
      filters: ['App\Api\ApiPlatform\Filter\FulltextSearchFilter']

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'model_region:read']
      openapiContext:
        description: 'Gibt eine OZG Modellregion zurück'