App\Entity\Onboarding\MonumentAuthority:
  #security: 'is_granted("PERMISSION_API_ONBOARDING")'
  attributes:
    pagination_items_per_page: 25
  ##description: 'Bauportal.NRW Untere Denkmalbehörde'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'monument_authority:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Einträgen für Bauportal.NRW Untere Denkmalbehörde zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'monument_authority:read']
      openapiContext:
        description: 'Gibt einen Eintrag für Bauportal.NRW Untere Denkmalbehörde zurück'