App\Entity\Onboarding\OnboardingDocument:
  #security: 'is_granted("PERMISSION_API_ONBOARDING")'
  attributes:
    pagination_items_per_page: 25
  ##description: 'Kommunalportal Basisdaten Dokumente'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'onboarding_document:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Kommunalportal Basisdaten Dokumente zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'onboarding_document:read']
      openapiContext:
        description: 'Gibt einen Eintrag der Kommunalportal Basisdaten Dokumente zurück'