App\Entity\Onboarding\OnboardingCommuneSolution:
  #security: 'is_granted("PERMISSION_API_ONBOARDING")'
  attributes:
    pagination_items_per_page: 25
  ##description: 'Kommunalportal Basisdaten Dienste'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'onboarding_commune_solution:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Kommunalportal Basisdaten Dienste zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'onboarding_commune_solution:read']
      openapiContext:
        description: 'Gibt einen Eintrag der Kommunalportal Basisdaten Dienste zurück'