App\Entity\Onboarding\Release:
  attributes:
    security: 'is_granted("PERMISSION_API_ONBOARDING")'
    pagination_items_per_page: 25
  description: 'Kommunalportal Go-Live'

  collectionOperations:
    get:
      method: 'GET'
      normalization_context:
        enable_max_depth: 1
        groups: ['collection:read', 'release:collection:read']
      openapi_context:
        summary: 'Gibt eine Liste mit Kommunalportal Go-Live zurück'

  itemOperations:
    get:
      method: 'GET'
      normalization_context:
        enable_max_depth: 1
        groups: ['item:read', 'release:read']
      openapi_context:
        summary: 'Gibt einen Eintrag der Kommunalportal Go-Live zurück'