App\Entity\Onboarding\Release:
  #security: 'is_granted("PERMISSION_API_ONBOARDING")'
  attributes:
    pagination_items_per_page: 25
  ##description: 'Kommunalportal Go-Live'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'release:collection:read']
      openapiContext:
        description: 'Gibt eine Liste mit Kommunalportal Go-Live zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'release:read']
      openapiContext:
        description: 'Gibt einen Eintrag der Kommunalportal Go-Live zurück'