App\Entity\Onboarding\ServiceAccount:
  attributes:
    security: 'is_granted("PERMISSION_API_ONBOARDING")'
    pagination_items_per_page: 25
  ##description: 'Kommunalportal Servicekonto NRW'

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalization_context:
        enable_max_depth: 1
        groups: ['collection:read', 'service_account:collection:read']
      openapi_context:
        summary: 'Gibt eine Liste mit Kommunalportal Servicekonto NRW zurück'

    ApiPlatform\Metadata\Get:
      normalization_context:
        enable_max_depth: 1
        groups: ['item:read', 'service_account:read']
      openapi_context:
        summary: 'Gibt einen Eintrag der Kommunalportal Servicekonto NRW zurück'