# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\ServiceSystem:
  #shortName: 'Leika-Leistungen'
  ##description: 'OZG Leistungen'
  attributes:
    pagination_items_per_page: 25

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'service_system:collection:read', 'service-system-situation-subject']
      openapiContext:
        description: 'Gibt eine Liste mit OZG Leistungen zurück'
      filters: ['App\Api\ApiPlatform\Filter\FulltextSearchFilter']

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'service_system:read', 'service-system-situation-subject']
      openapiContext:
        description: 'Gibt eine OZG Leistung zurück'