# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\Service:
  #shortName: 'Leika-Leistungen'
  #description: 'An offer from my shop'
  attributes:
    pagination_items_per_page: 25
    #normalization_context:
    #  groups: ['article_read']

  collectionOperations:
    get: ~
#    post:
#      security: 'is_granted("ROLE_ADMIN")'

  itemOperations:
    get:
      method: 'GET'
#    put:
#      method: 'PUT'