# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\Situation:
  #shortName: 'Leika-Leistungen'
  description: 'OZG Lagen'
  attributes:
    pagination_items_per_page: 25

  collectionOperations:
    get:
      method: 'GET'
      normalization_context:
        enable_max_depth: 1
        groups: ['collection:read', 'situation:collection:read', 'service-system-situation-subject']
      openapi_context:
        summary: 'Gibt eine Liste mit OZG Lagen zurück'
  #    post:
  #      security: 'is_granted("ROLE_ADMIN")'

  itemOperations:
    get:
      method: 'GET'
      normalization_context:
        enable_max_depth: 1
        groups: ['item:read', 'situation:read', 'service-system-situation-subject']
      openapi_context:
        summary: 'Gibt eine OZG Lage zurück'
  #    put:
  #      method: 'PUT'