# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\Situation:
  #shortName: 'Leika-Leistungen'
  ##description: 'OZG Lagen'
  attributes:
    pagination_items_per_page: 25

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'situation:collection:read', 'service-system-situation-subject']
      openapiContext:
        description: 'Gibt eine Liste mit OZG Lagen zurück'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'situation:read', 'service-system-situation-subject']
      openapiContext:
        description: 'Gibt eine OZG Lage zurück'