# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\Subject:
  #shortName: 'Leika-Leistungen'
  ##description: 'OZG Themenfelder'
  attributes:
    pagination_items_per_page: 25

  operations:
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        enable_max_depth: 1
        groups: ['collection:read', 'subject:collection:read', 'service-system-situation-subject']
      openapiContext:
        description: 'Gibt eine Liste mit OZG Themenfeldern zurück'
#    post:
#      #security: 'is_granted("ROLE_ADMIN")'

    ApiPlatform\Metadata\Get:
      normalizationContext:
        enable_max_depth: 1
        groups: ['item:read', 'subject:read', 'service-system-situation-subject']
      openapiContext:
        description: 'Gibt ein OZG Themenfeld zurück'
#    put:
#      method: 'PUT'