# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\Application\ApplicationInterface:
  attributes:
    id:
      groups: ['collection:read', 'item:read']
    name:
      groups: ['collection:read', 'item:read']
    description:
      groups: ['item:read']
#    application:
#      groups: ['item:read']
    connectedSpecializedProcedures:
      groups: ['item:read', 'specialized_procedure:read']
