# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\StateGroup\Bureau:
  attributes:
    id:
      groups: ['collection:read', 'item:read']
    name:
      groups: ['collection:read', 'item:read']
    description:
      groups: ['service:read', 'service_system:read', 'bureau:read']
    serviceSystems:
      ignore: true
    serviceAuthorities:
      ignore: true