# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\FormServer:
  attributes:
    id:
      groups: ['collection:read', 'item:read']
    name:
      groups: ['collection:read', 'item:read']
    url:
      groups: ['form_server:collection:read', 'form_server:read']
    formServerSolutions:
      groups: ['form_server:read']
