# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\Laboratory:
  attributes:
    id:
      groups: ['collection:read', 'read']
    name:
      groups: ['collection:read', 'read']