# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
# https://www.thinkbean.com/drupal-development-blog/defining-api-platform-resources-serialization-groups-yaml
App\Entity\Priority:
  attributes:
    id:
      groups: ['collection:read', 'read']
    name:
      groups: ['collection:read', 'read']