# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\Priority:
  attributes:
    id:
      groups: ['collection:read', 'item:read']
    name:
      groups: ['collection:read', 'item:read']
    description:
      groups: ['priority:collection:read', 'priority:read']
    prevStatus:
      ignore: true
    nextStatus:
      ignore: true
    serviceSystems:
      ignore: true