App\Entity\Onboarding\ServiceAccount:
  attributes:
    id:
      groups: [ 'collection:read', 'item:read' ]
    street:
      groups: [ 'item:read' ]
    town:
      groups: [ 'item:read' ]
    zipCode:
      groups: [ 'item:read' ]
    email:
      groups: [ 'item:read' ]
    phoneNumber:
      groups: [ 'item:read' ]
    mobileNumber:
      groups: [ 'item:read' ]
    paymentProviderAccountId:
      groups: [ 'item:read' ]
    paymentProvider:
      groups: [ 'item:read' ]
    paymentUser:
      groups: [ 'item:read' ]
    mandatorEmail:
      groups: [ 'item:read' ]
    paymentOperator:
      groups: [ 'item:read' ]
    accountMandatorState:
      groups: [ 'item:read' ]
    answerUrl1:
      groups: [ 'item:read' ]
    clientId:
      groups: [ 'item:read' ]
    clientPassword:
      groups: [ 'item:read' ]
    answerUrl2:
      groups: [ 'item:read' ]
    clientId2:
      groups: [ 'item:read' ]
    clientPassword2:
      groups: [ 'item:read' ]