# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\ServiceSolution:
  attributes:
    id:
      groups: ['collection:read', 'item:read']
    service:
      groups: ['solution:read']
    solution:
      groups: ['service:read']
    maturity:
      groups: ['service:read', 'solution:read']