# https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters
App\Entity\ServiceSystem:
  attributes:
    id:
      groups: ['collection:read', 'item:read']
    name:
      groups: ['collection:read', 'item:read']
    description:
      groups: ['service_system:collection:read', 'service_system:read']
    serviceKey:
      groups: ['collection:read', 'item:read']
    slug:
      groups: ['service_system:collection:read', 'service_system:read']
    jurisdictions:
      groups: ['service_system:collection:read', 'service_system:read']
      max_depth: 1
    situation:
      groups: ['service_system:collection:read', 'service_system:read', 'service-system-situation-subject']
      max_depth: 1
    priority:
      groups: ['service_system:collection:read', 'service_system:read']
    status:
      groups: ['service_system:collection:read', 'service_system:read']
    stateMinistries:
      groups: ['service_system:read']
      max_depth: 1
    bureaus:
      groups: ['service_system:read']
      max_depth: 1
    ruleAuthorities:
      groups: ['service_system:read']
      max_depth: 1
    authorityBureaus:
      groups: ['service_system:read']
      max_depth: 1
    authorityStateMinistries:
      groups: ['service_system:read']
      max_depth: 1
    communeTypes:
      groups: ['service_system:read']
      max_depth: 1
    services:
      groups: ['service_system:read']
      max_depth: 1
    solutions:
      groups: ['service_system:read']
      max_depth: 1
    laboratories:
      groups: ['service_system:read']
      max_depth: 1
    implementationProjects:
      groups: ['service_system:read']
      max_depth: 1
    publishedModelRegionProjects:
      groups: ['service_system:read']
      max_depth: 1