<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220327175644 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ozg_application_audit (id INT NOT NULL, rev INT NOT NULL, description LONGTEXT DEFAULT NULL, accessibility_test_conducted LONGTEXT DEFAULT NULL, privacy LONGTEXT DEFAULT NULL, archive LONGTEXT DEFAULT NULL, in_house_development INT DEFAULT NULL, accessibility_test_organisation_others LONGTEXT DEFAULT NULL, accessibility_self_testing TINYINT(1) DEFAULT NULL, accessibility_test_result_type INT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(20) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, url VARCHAR(2048) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_f7eb9ff59e5b71af68e01e6a4ece0136_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_commune_audit (id INT NOT NULL, rev INT NOT NULL, organisation_id INT DEFAULT NULL, constituency_id INT DEFAULT NULL, administrative_district_id INT DEFAULT NULL, commune_type_id INT DEFAULT NULL, created_by INT DEFAULT NULL, modified_by INT DEFAULT NULL, slug VARCHAR(128) DEFAULT NULL, main_email VARCHAR(255) DEFAULT NULL, official_community_key VARCHAR(255) DEFAULT NULL, regional_key VARCHAR(255) DEFAULT NULL, transparency_portal_url VARCHAR(2048) DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(20) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, contact LONGTEXT DEFAULT NULL, url VARCHAR(2048) DEFAULT NULL, administration_email VARCHAR(255) DEFAULT NULL, administration_phone_number VARCHAR(100) DEFAULT NULL, administration_fax_number VARCHAR(100) DEFAULT NULL, administration_url VARCHAR(2048) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_b954891437059cf87d65bd7c260ed200_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_implementation_project_audit (id INT NOT NULL, rev INT NOT NULL, status_id INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, project_start_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', concept_status_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', implementation_status_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', commissioning_status_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', piloting_status_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', nationwide_rollout_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', notes LONGTEXT DEFAULT NULL, efa_type INT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) DEFAULT NULL, slug VARCHAR(128) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_6420bf21b0ee35e6328b61eca869f0c8_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_model_region_project_audit (id INT NOT NULL, rev INT NOT NULL, description LONGTEXT DEFAULT NULL, project_lead LONGTEXT DEFAULT NULL, project_start_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', project_concept_start_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', project_implementation_start_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', project_end_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', usp LONGTEXT DEFAULT NULL, communes_benefits LONGTEXT DEFAULT NULL, transferable_service LONGTEXT DEFAULT NULL, transferable_start LONGTEXT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) DEFAULT NULL, import_id INT DEFAULT NULL, import_source VARCHAR(100) DEFAULT NULL, slug VARCHAR(128) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_29d537fdeee8743e230de0c10ab9be1a_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_audit (id INT NOT NULL, rev INT NOT NULL, commune_id INT DEFAULT NULL, service_provider_id INT DEFAULT NULL, created_by INT DEFAULT NULL, modified_by INT DEFAULT NULL, group_email VARCHAR(255) DEFAULT NULL, status INT DEFAULT NULL, completion_rate INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, message_count INT DEFAULT NULL, data_completeness_confirmed TINYINT(1) DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', hidden TINYINT(1) DEFAULT NULL, record_type VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_9f55b69c076f4b9245f7a814cf3cf000_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_base_info_audit (id INT NOT NULL, rev INT NOT NULL, privacy_text LONGTEXT DEFAULT NULL, privacy_url VARCHAR(2048) DEFAULT NULL, imprint_text LONGTEXT DEFAULT NULL, imprint_url VARCHAR(2048) DEFAULT NULL, accessibility LONGTEXT DEFAULT NULL, opening_hours LONGTEXT DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, image_size INT DEFAULT NULL, ip_address VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_0b51067b1c5d92c58784bf426c6e99b1_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_contact_audit (id INT NOT NULL, rev INT NOT NULL, commune_id INT DEFAULT NULL, commune_info_id INT DEFAULT NULL, epayment_id INT DEFAULT NULL, form_solution_id INT DEFAULT NULL, service_account_id INT DEFAULT NULL, xta_server_id INT DEFAULT NULL, contact_type VARCHAR(50) DEFAULT NULL, external_user_name VARCHAR(255) DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', gender INT DEFAULT NULL, title VARCHAR(100) DEFAULT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(100) DEFAULT NULL, mobile_number VARCHAR(100) DEFAULT NULL, hidden TINYINT(1) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(20) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_a7287f5284d5b43557dbce6265b8b6ed_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_document_audit (id INT NOT NULL, rev INT NOT NULL, onboarding_id INT DEFAULT NULL, document_type VARCHAR(50) DEFAULT NULL, file_size INT DEFAULT NULL, local_name VARCHAR(255) DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_53b3a7d1156cdee73abd2972fc3db6da_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_epayment_audit (id INT NOT NULL, rev INT NOT NULL, payment_operator_id INT DEFAULT NULL, payment_provider_account_id VARCHAR(255) DEFAULT NULL, payment_provider VARCHAR(255) DEFAULT NULL, mandator_email VARCHAR(255) DEFAULT NULL, test_ip_address VARCHAR(255) DEFAULT NULL, client_number_integration VARCHAR(255) DEFAULT NULL, client_number_production VARCHAR(255) DEFAULT NULL, manager_number VARCHAR(255) DEFAULT NULL, budget_office VARCHAR(255) DEFAULT NULL, object_number VARCHAR(255) DEFAULT NULL, cash_register_personal_account_number VARCHAR(255) DEFAULT NULL, indicator_dunning_procedure VARCHAR(255) DEFAULT NULL, booking_text VARCHAR(255) DEFAULT NULL, description_of_the_booking_list VARCHAR(255) DEFAULT NULL, manager_no VARCHAR(255) DEFAULT NULL, application_name VARCHAR(255) DEFAULT NULL, length_receipt_number VARCHAR(255) DEFAULT NULL, cash_register_check_procedure_status TINYINT(1) DEFAULT NULL, length_first_account_assignment_information VARCHAR(255) DEFAULT NULL, content_first_account_assignment_information LONGTEXT DEFAULT NULL, length_second_account_assignment_information VARCHAR(255) DEFAULT NULL, content_second_account_assignment_information LONGTEXT DEFAULT NULL, xfinance_file_required TINYINT(1) DEFAULT NULL, xfinance_file_days JSON DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(20) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(100) DEFAULT NULL, mobile_number VARCHAR(100) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_3fdcb4f46c7e2bca10f70fa204eb1c8b_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_epayment_project_audit (id INT NOT NULL, rev INT NOT NULL, epayment_id INT DEFAULT NULL, provider_type VARCHAR(50) DEFAULT NULL, project_environment VARCHAR(50) DEFAULT NULL, project_id VARCHAR(100) DEFAULT NULL, project_password VARCHAR(255) DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', hidden TINYINT(1) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_3b91014543761b1daff36b23139d0d15_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_epayment_service_audit (id INT NOT NULL, rev INT NOT NULL, solution_id INT DEFAULT NULL, epayment_id INT DEFAULT NULL, booking_text LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, value_first_account_assignment_information LONGTEXT DEFAULT NULL, value_second_account_assignment_information LONGTEXT DEFAULT NULL, cost_unit LONGTEXT DEFAULT NULL, payers LONGTEXT DEFAULT NULL, product_description LONGTEXT DEFAULT NULL, tax_number LONGTEXT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', hidden TINYINT(1) DEFAULT NULL, position INT DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_3beb0e09f70fa62179752d7e3cbd5daf_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_form_solution_audit (id INT NOT NULL, rev INT NOT NULL, privacy_text LONGTEXT DEFAULT NULL, privacy_url VARCHAR(2048) DEFAULT NULL, imprint_text LONGTEXT DEFAULT NULL, imprint_url VARCHAR(2048) DEFAULT NULL, accessibility LONGTEXT DEFAULT NULL, opening_hours LONGTEXT DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, image_size INT DEFAULT NULL, letterhead_address LONGTEXT DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_8f40610a82fbf6f966e4465eaf2c029e_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_release_audit (id INT NOT NULL, rev INT NOT NULL, release_status INT DEFAULT NULL, release_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', release_confirmed TINYINT(1) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(20) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(100) DEFAULT NULL, mobile_number VARCHAR(100) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_629dbfc2c452c544c000e80ebc9fe740_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_service_account_audit (id INT NOT NULL, rev INT NOT NULL, payment_operator_id INT DEFAULT NULL, payment_provider_account_id VARCHAR(255) DEFAULT NULL, payment_provider VARCHAR(255) DEFAULT NULL, mandator_email VARCHAR(255) DEFAULT NULL, account_mandator_state INT DEFAULT NULL, answer_url_1 VARCHAR(1024) DEFAULT NULL, client_id VARCHAR(255) DEFAULT NULL, client_password VARCHAR(255) DEFAULT NULL, answer_url_2 VARCHAR(1024) DEFAULT NULL, client_id_2 VARCHAR(255) DEFAULT NULL, client_password_2 VARCHAR(255) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(20) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(100) DEFAULT NULL, mobile_number VARCHAR(100) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_e07e4f5bfa32e3a5ea45bf1c7b63f188_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_onboarding_xta_server_audit (id INT NOT NULL, rev INT NOT NULL, application_type INT DEFAULT NULL, intermediary_operator_type INT DEFAULT NULL, state VARCHAR(100) DEFAULT NULL, authority_category VARCHAR(100) DEFAULT NULL, organizational_key VARCHAR(100) DEFAULT NULL, comment LONGTEXT DEFAULT NULL, osci_private_key_password VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_0fa9fb29e6489b45ae6d4f73e6bffabe_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_service_audit (id INT NOT NULL, rev INT NOT NULL, status_id INT DEFAULT NULL, service_system_id INT DEFAULT NULL, priority_id INT DEFAULT NULL, created_by INT DEFAULT NULL, modified_by INT DEFAULT NULL, slug VARCHAR(128) DEFAULT NULL, service_type VARCHAR(255) DEFAULT NULL, legal_basis LONGTEXT DEFAULT NULL, laws LONGTEXT DEFAULT NULL, law_shortcuts VARCHAR(255) DEFAULT NULL, relevance1 TINYINT(1) DEFAULT NULL, relevance2 TINYINT(1) DEFAULT NULL, inherit_jurisdictions TINYINT(1) DEFAULT NULL, inherit_state_ministries TINYINT(1) DEFAULT NULL, inherit_bureaus TINYINT(1) DEFAULT NULL, inherit_rule_authorities TINYINT(1) DEFAULT NULL, authority_inherit_state_ministries TINYINT(1) DEFAULT NULL, authority_inherit_bureaus TINYINT(1) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, inherit_commune_types TINYINT(1) DEFAULT NULL, name VARCHAR(1024) DEFAULT NULL, service_key VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', hidden TINYINT(1) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_f9a2079cbeb61321af9ee509331b15d3_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_service_provider_audit (id INT NOT NULL, rev INT NOT NULL, organisation_id INT DEFAULT NULL, data_center_id INT DEFAULT NULL, short_name VARCHAR(255) DEFAULT NULL, enable_payment_provider TINYINT(1) DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(20) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, contact LONGTEXT DEFAULT NULL, url VARCHAR(2048) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_49b6ab3f86a480d392f0b95878026c40_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_service_system_audit (id INT NOT NULL, rev INT NOT NULL, status_id INT DEFAULT NULL, situation_id INT DEFAULT NULL, priority_id INT DEFAULT NULL, created_by INT DEFAULT NULL, modified_by INT DEFAULT NULL, slug VARCHAR(128) DEFAULT NULL, name VARCHAR(1024) DEFAULT NULL, service_key VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', hidden TINYINT(1) DEFAULT NULL, contact LONGTEXT DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_809aaa24c311da0d410f9ea87a143e68_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_solution_audit (id INT NOT NULL, rev INT NOT NULL, status_id INT DEFAULT NULL, maturity_id INT DEFAULT NULL, confidence_level_id INT DEFAULT NULL, created_by INT DEFAULT NULL, modified_by INT DEFAULT NULL, name VARCHAR(1024) DEFAULT NULL, custom_provider LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, commune_type VARCHAR(255) DEFAULT NULL, is_published TINYINT(1) DEFAULT NULL, enabled_municipal_portal TINYINT(1) DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', contact LONGTEXT DEFAULT NULL, hidden TINYINT(1) DEFAULT NULL, import_id INT DEFAULT NULL, import_source VARCHAR(100) DEFAULT NULL, slug VARCHAR(128) DEFAULT NULL, url VARCHAR(2048) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_916f5b1c3a6c66a0bf2321255f39043d_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_audit (id INT NOT NULL, rev INT NOT NULL, created_by INT DEFAULT NULL, modified_by INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_9f488164f3c0ce5e8a2f70edb2ba47f4_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE revisions (id INT AUTO_INCREMENT NOT NULL, timestamp DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', username VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('DROP TABLE ozg_implementation');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ozg_implementation (id INT AUTO_INCREMENT NOT NULL, is_final TINYINT(1) NOT NULL, is_planned TINYINT(1) NOT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, hidden TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE ozg_application_audit');
        $this->addSql('DROP TABLE ozg_commune_audit');
        $this->addSql('DROP TABLE ozg_implementation_project_audit');
        $this->addSql('DROP TABLE ozg_model_region_project_audit');
        $this->addSql('DROP TABLE ozg_onboarding_audit');
        $this->addSql('DROP TABLE ozg_onboarding_base_info_audit');
        $this->addSql('DROP TABLE ozg_onboarding_contact_audit');
        $this->addSql('DROP TABLE ozg_onboarding_document_audit');
        $this->addSql('DROP TABLE ozg_onboarding_epayment_audit');
        $this->addSql('DROP TABLE ozg_onboarding_epayment_project_audit');
        $this->addSql('DROP TABLE ozg_onboarding_epayment_service_audit');
        $this->addSql('DROP TABLE ozg_onboarding_form_solution_audit');
        $this->addSql('DROP TABLE ozg_onboarding_release_audit');
        $this->addSql('DROP TABLE ozg_onboarding_service_account_audit');
        $this->addSql('DROP TABLE ozg_onboarding_xta_server_audit');
        $this->addSql('DROP TABLE ozg_service_audit');
        $this->addSql('DROP TABLE ozg_service_provider_audit');
        $this->addSql('DROP TABLE ozg_service_system_audit');
        $this->addSql('DROP TABLE ozg_solution_audit');
        $this->addSql('DROP TABLE ozg_specialized_procedure_audit');
        $this->addSql('DROP TABLE revisions');
    }
}
