<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20221115214631 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remove application tables; instead move tables and properties to specialiezd procedures';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ozg_application_accessibility_document DROP FOREIGN KEY FK_D47F606A3E030ACD');
        $this->addSql('ALTER TABLE ozg_application_accessibility_test_organisations DROP FOREIGN KEY FK_1EEFD72B3E030ACD');
        $this->addSql('ALTER TABLE ozg_application_business_premises DROP FOREIGN KEY FK_21854A6C3E030ACD');
        $this->addSql('ALTER TABLE ozg_application_category_mm DROP FOREIGN KEY FK_1E359B913E030ACD');
        $this->addSql('ALTER TABLE ozg_application_commune DROP FOREIGN KEY FK_F8176703E030ACD');
        $this->addSql('ALTER TABLE ozg_application_interface DROP FOREIGN KEY FK_938490613E030ACD');
        $this->addSql('ALTER TABLE ozg_application_manufacturer DROP FOREIGN KEY FK_22C1A6C93E030ACD');
        $this->addSql('ALTER TABLE ozg_application_module DROP FOREIGN KEY FK_D70098A83E030ACD');
        $this->addSql('ALTER TABLE ozg_application_service_provider DROP FOREIGN KEY FK_D9E901BC3E030ACD');
        $this->addSql('ALTER TABLE ozg_application_category DROP FOREIGN KEY FK_1116C425727ACA70');
        $this->addSql('ALTER TABLE ozg_application_category_mm DROP FOREIGN KEY FK_1E359B9112469DE2');
        $this->addSql('ALTER TABLE ozg_application_interface_specialized_procedures DROP FOREIGN KEY FK_976F13CF81E22DB');
        $this->addSql('CREATE TABLE ozg_meta_service_specialized_procedure (id INT AUTO_INCREMENT NOT NULL, service_id INT DEFAULT NULL, specialized_procedure_id INT DEFAULT NULL, created_by INT DEFAULT NULL, modified_by INT DEFAULT NULL, disabled TINYINT(1) DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', INDEX IDX_EEC9C734ED5CA9E6 (service_id), INDEX IDX_EEC9C734452D2882 (specialized_procedure_id), INDEX IDX_EEC9C734DE12AB56 (created_by), INDEX IDX_EEC9C73425F94802 (modified_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_category_mm (application_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_422119973E030ACD (application_id), INDEX IDX_4221199712469DE2 (category_id), PRIMARY KEY(application_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_business_premises (application_id INT NOT NULL, organisation_id INT NOT NULL, INDEX IDX_86275D9F3E030ACD (application_id), INDEX IDX_86275D9F9E6B1585 (organisation_id), PRIMARY KEY(application_id, organisation_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_accessibility_test_organisations (application_id INT NOT NULL, organisation_id INT NOT NULL, INDEX IDX_3B1087D73E030ACD (application_id), INDEX IDX_3B1087D79E6B1585 (organisation_id), PRIMARY KEY(application_id, organisation_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_accessibility_document (id INT AUTO_INCREMENT NOT NULL, application_id INT DEFAULT NULL, file_size INT DEFAULT NULL, local_name VARCHAR(255) DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) NOT NULL, INDEX IDX_2D9F86E13E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_category (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, position INT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) NOT NULL, import_id INT DEFAULT NULL, import_source VARCHAR(100) DEFAULT NULL, INDEX IDX_5052DFF9727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_interface (id INT AUTO_INCREMENT NOT NULL, application_id INT NOT NULL, description LONGTEXT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) NOT NULL, INDEX IDX_1CA04A853E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_interface_connected (application_interface_id INT NOT NULL, specialized_procedure_id INT NOT NULL, INDEX IDX_1688E34281E22DB (application_interface_id), INDEX IDX_1688E342452D2882 (specialized_procedure_id), PRIMARY KEY(application_interface_id, specialized_procedure_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_module (id INT AUTO_INCREMENT NOT NULL, application_id INT NOT NULL, description LONGTEXT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) NOT NULL, INDEX IDX_69B755423E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE ozg_meta_service_specialized_procedure ADD CONSTRAINT FK_EEC9C734ED5CA9E6 FOREIGN KEY (service_id) REFERENCES ozg_service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ozg_meta_service_specialized_procedure ADD CONSTRAINT FK_EEC9C734452D2882 FOREIGN KEY (specialized_procedure_id) REFERENCES ozg_specialized_procedure (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ozg_meta_service_specialized_procedure ADD CONSTRAINT FK_EEC9C734DE12AB56 FOREIGN KEY (created_by) REFERENCES mb_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ozg_meta_service_specialized_procedure ADD CONSTRAINT FK_EEC9C73425F94802 FOREIGN KEY (modified_by) REFERENCES mb_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_category_mm ADD CONSTRAINT FK_422119973E030ACD FOREIGN KEY (application_id) REFERENCES ozg_specialized_procedure (id)');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_category_mm ADD CONSTRAINT FK_4221199712469DE2 FOREIGN KEY (category_id) REFERENCES ozg_specialized_procedure_category (id)');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_business_premises ADD CONSTRAINT FK_86275D9F3E030ACD FOREIGN KEY (application_id) REFERENCES ozg_specialized_procedure (id)');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_business_premises ADD CONSTRAINT FK_86275D9F9E6B1585 FOREIGN KEY (organisation_id) REFERENCES ozg_organisation (id)');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_accessibility_test_organisations ADD CONSTRAINT FK_3B1087D73E030ACD FOREIGN KEY (application_id) REFERENCES ozg_specialized_procedure (id)');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_accessibility_test_organisations ADD CONSTRAINT FK_3B1087D79E6B1585 FOREIGN KEY (organisation_id) REFERENCES ozg_organisation (id)');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_accessibility_document ADD CONSTRAINT FK_2D9F86E13E030ACD FOREIGN KEY (application_id) REFERENCES ozg_specialized_procedure (id)');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_category ADD CONSTRAINT FK_5052DFF9727ACA70 FOREIGN KEY (parent_id) REFERENCES ozg_specialized_procedure_category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_interface ADD CONSTRAINT FK_1CA04A853E030ACD FOREIGN KEY (application_id) REFERENCES ozg_specialized_procedure (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_interface_connected ADD CONSTRAINT FK_1688E34281E22DB FOREIGN KEY (application_interface_id) REFERENCES ozg_specialized_procedure_interface (id)');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_interface_connected ADD CONSTRAINT FK_1688E342452D2882 FOREIGN KEY (specialized_procedure_id) REFERENCES ozg_specialized_procedure (id)');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_module ADD CONSTRAINT FK_69B755423E030ACD FOREIGN KEY (application_id) REFERENCES ozg_specialized_procedure (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE IF EXISTS ozg_application');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_accessibility_document');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_accessibility_test_organisations');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_accessibility_test_organisations_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_business_premises');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_business_premises_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_category');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_category_mm');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_category_mm_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_commune');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_commune_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_interface');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_interface_specialized_procedures');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_manufacturer');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_manufacturer_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_module');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_service_provider');
        $this->addSql('DROP TABLE IF EXISTS ozg_application_service_provider_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_commune_central_association_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_commune_laboratory_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_commune_portals_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_communes_service_provider_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_implementation_project_contact_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_implementation_project_fim_export_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_implementation_project_funding_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_implementation_project_laboratory_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_implementation_project_organisation_interested_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_implementation_project_organisation_leaders_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_implementation_project_organisation_participation_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_implementation_project_service_system_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_implementation_project_solution_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_model_region_project_category_mm_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_model_region_project_organisation_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_model_region_project_solutions_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_authority_bureau_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_authority_ministry_state_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_commune_type_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_jurisdiction_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_ministry_state_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_rule_authority_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_specialized_procedures_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_system_authority_bureau_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_system_authority_ministry_state_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_system_commune_type_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_system_jurisdiction_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_system_rule_authority_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_service_system_solution_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_services_portals_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_solution_analog_service_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_solution_contact_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_solution_open_data_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_solution_service_provider_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_solutions_authentications_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_solutions_portals_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_solutions_specialized_procedures_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_specialized_procedure_commune_audit');
        $this->addSql('DROP TABLE IF EXISTS ozg_specialized_procedure_service_provider_audit');
        $this->addSql('ALTER TABLE ozg_specialized_procedure ADD accessibility_test_conducted LONGTEXT DEFAULT NULL, ADD privacy LONGTEXT DEFAULT NULL, ADD archive LONGTEXT DEFAULT NULL, ADD in_house_development INT DEFAULT NULL, ADD accessibility_test_organisation_others LONGTEXT DEFAULT NULL, ADD accessibility_self_testing TINYINT(1) DEFAULT NULL, ADD accessibility_test_result_type INT NOT NULL, ADD street VARCHAR(255) DEFAULT NULL, ADD zip_code VARCHAR(20) DEFAULT NULL, ADD town VARCHAR(255) DEFAULT NULL, ADD url VARCHAR(2048) DEFAULT NULL');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_audit ADD accessibility_test_conducted LONGTEXT DEFAULT NULL, ADD privacy LONGTEXT DEFAULT NULL, ADD archive LONGTEXT DEFAULT NULL, ADD in_house_development INT DEFAULT NULL, ADD accessibility_test_organisation_others LONGTEXT DEFAULT NULL, ADD accessibility_self_testing TINYINT(1) DEFAULT NULL, ADD accessibility_test_result_type INT DEFAULT NULL, ADD street VARCHAR(255) DEFAULT NULL, ADD zip_code VARCHAR(20) DEFAULT NULL, ADD town VARCHAR(255) DEFAULT NULL, ADD url VARCHAR(2048) DEFAULT NULL');
        $this->addSql('ALTER TABLE ozg_meta_service_specialized_procedure ADD solution_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ozg_meta_service_specialized_procedure ADD CONSTRAINT FK_EEC9C7341C0BE183 FOREIGN KEY (solution_id) REFERENCES ozg_solution (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_EEC9C7341C0BE183 ON ozg_meta_service_specialized_procedure (solution_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ozg_specialized_procedure_category_mm DROP FOREIGN KEY FK_4221199712469DE2');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_category DROP FOREIGN KEY FK_5052DFF9727ACA70');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_interface_connected DROP FOREIGN KEY FK_1688E34281E22DB');
        $this->addSql('CREATE TABLE ozg_application (id INT AUTO_INCREMENT NOT NULL, description LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, accessibility_test_conducted LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, privacy LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, archive LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, in_house_development INT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, hidden TINYINT(1) NOT NULL, street VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, zip_code VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, town VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, url VARCHAR(2048) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, accessibility_test_organisation_others LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, accessibility_self_testing TINYINT(1) DEFAULT NULL, accessibility_test_result_type INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_accessibility_document (id INT AUTO_INCREMENT NOT NULL, application_id INT DEFAULT NULL, file_size INT DEFAULT NULL, local_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, hidden TINYINT(1) NOT NULL, INDEX IDX_D47F606A3E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_accessibility_test_organisations (application_id INT NOT NULL, organisation_id INT NOT NULL, INDEX IDX_1EEFD72B3E030ACD (application_id), INDEX IDX_1EEFD72B9E6B1585 (organisation_id), PRIMARY KEY(application_id, organisation_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_accessibility_test_organisations_audit (application_id INT NOT NULL, organisation_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_9aa5a6806c9824e63e0fa45482ecfdbb_idx (rev), PRIMARY KEY(application_id, organisation_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_audit (id INT NOT NULL, rev INT NOT NULL, description LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, accessibility_test_conducted LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, privacy LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, archive LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, in_house_development INT DEFAULT NULL, accessibility_test_organisation_others LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, accessibility_self_testing TINYINT(1) DEFAULT NULL, accessibility_test_result_type INT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, hidden TINYINT(1) DEFAULT NULL, street VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, zip_code VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, town VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, url VARCHAR(2048) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_f7eb9ff59e5b71af68e01e6a4ece0136_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_business_premises (application_id INT NOT NULL, organisation_id INT NOT NULL, INDEX IDX_21854A6C3E030ACD (application_id), INDEX IDX_21854A6C9E6B1585 (organisation_id), PRIMARY KEY(application_id, organisation_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_business_premises_audit (application_id INT NOT NULL, organisation_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_f9a30a79069807e23fd61e692b4324c8_idx (rev), PRIMARY KEY(application_id, organisation_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_category (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, description LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, position INT DEFAULT NULL, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, hidden TINYINT(1) NOT NULL, import_id INT DEFAULT NULL, import_source VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_1116C425727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_category_mm (application_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_1E359B913E030ACD (application_id), INDEX IDX_1E359B9112469DE2 (category_id), PRIMARY KEY(application_id, category_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_category_mm_audit (application_id INT NOT NULL, category_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_e2bc08bb767e9a58c3811e88d4e6f79d_idx (rev), PRIMARY KEY(application_id, category_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_commune (application_id INT NOT NULL, commune_id INT NOT NULL, INDEX IDX_F8176703E030ACD (application_id), INDEX IDX_F817670131A4F72 (commune_id), PRIMARY KEY(application_id, commune_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_commune_audit (application_id INT NOT NULL, commune_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_5ed754c610ba9af6abb3a1bdc78e61df_idx (rev), PRIMARY KEY(application_id, commune_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_interface (id INT AUTO_INCREMENT NOT NULL, application_id INT NOT NULL, description LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, hidden TINYINT(1) NOT NULL, INDEX IDX_938490613E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_interface_specialized_procedures (application_interface_id INT NOT NULL, specialized_procedure_id INT NOT NULL, INDEX IDX_976F13CF81E22DB (application_interface_id), INDEX IDX_976F13CF452D2882 (specialized_procedure_id), PRIMARY KEY(application_interface_id, specialized_procedure_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_manufacturer (application_id INT NOT NULL, manufacturer_id INT NOT NULL, INDEX IDX_22C1A6C93E030ACD (application_id), INDEX IDX_22C1A6C9A23B42D (manufacturer_id), PRIMARY KEY(application_id, manufacturer_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_manufacturer_audit (application_id INT NOT NULL, manufacturer_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_c8e4e590935cf3a21cf29fcc15d96903_idx (rev), PRIMARY KEY(application_id, manufacturer_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_module (id INT AUTO_INCREMENT NOT NULL, application_id INT NOT NULL, description LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, modified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, hidden TINYINT(1) NOT NULL, INDEX IDX_D70098A83E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_service_provider (application_id INT NOT NULL, service_provider_id INT NOT NULL, INDEX IDX_D9E901BC3E030ACD (application_id), INDEX IDX_D9E901BCC6C98E06 (service_provider_id), PRIMARY KEY(application_id, service_provider_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_application_service_provider_audit (application_id INT NOT NULL, service_provider_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_6a9ba0f0d83adff70fc24d0bc69f3471_idx (rev), PRIMARY KEY(application_id, service_provider_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_commune_central_association_audit (commune_id INT NOT NULL, central_association_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_71a0e3ad95a932328b8a00091e92ccfa_idx (rev), PRIMARY KEY(commune_id, central_association_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_commune_laboratory_audit (commune_id INT NOT NULL, laboratory_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_bda6505e66583e168e09a17bfd52d169_idx (rev), PRIMARY KEY(commune_id, laboratory_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_commune_portals_audit (commune_id INT NOT NULL, portal_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_c83dbd793f1d3f1548a60fdb003d0fb0_idx (rev), PRIMARY KEY(commune_id, portal_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_communes_service_provider_audit (commune_id INT NOT NULL, service_provider_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_ed59e2b776a706f6452dd96ff3f48053_idx (rev), PRIMARY KEY(commune_id, service_provider_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_implementation_project_contact_audit (implementation_project_id INT NOT NULL, contact_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_74585fbf1bca4d449dba23fd6b64e2c4_idx (rev), PRIMARY KEY(implementation_project_id, contact_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_implementation_project_fim_export_audit (implementation_project_id INT NOT NULL, contact_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_6bc99962fb9884f1ba3de0100c7dc224_idx (rev), PRIMARY KEY(implementation_project_id, contact_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_implementation_project_funding_audit (implementation_project_id INT NOT NULL, funding_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_395d97e5f96346b5f0eec020a5dff784_idx (rev), PRIMARY KEY(implementation_project_id, funding_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_implementation_project_laboratory_audit (implementation_project_id INT NOT NULL, laboratory_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_b4971eba77436ce80cc2774056be9feb_idx (rev), PRIMARY KEY(implementation_project_id, laboratory_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_implementation_project_organisation_interested_audit (implementation_project_id INT NOT NULL, organisation_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_54cbf67a44d24a83d85c1f0a10446b06_idx (rev), PRIMARY KEY(implementation_project_id, organisation_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_implementation_project_organisation_leaders_audit (implementation_project_id INT NOT NULL, organisation_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_0d7014eaadca7bf8de72d33efac28930_idx (rev), PRIMARY KEY(implementation_project_id, organisation_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_implementation_project_organisation_participation_audit (implementation_project_id INT NOT NULL, organisation_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_e4c33cbdf443606ef2b25eb407e930ae_idx (rev), PRIMARY KEY(implementation_project_id, organisation_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_implementation_project_service_system_audit (implementation_project_id INT NOT NULL, service_system_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_e547f89ad8f54b9eff915eccf875c446_idx (rev), PRIMARY KEY(implementation_project_id, service_system_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_implementation_project_solution_audit (implementation_project_id INT NOT NULL, solution_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_48cc3f9de93acec892b955b0899be813_idx (rev), PRIMARY KEY(implementation_project_id, solution_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_model_region_project_category_mm_audit (project_id INT NOT NULL, category_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_11b3d175122145efafe60400b9ae8a3a_idx (rev), PRIMARY KEY(project_id, category_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_model_region_project_organisation_audit (model_region_project_id INT NOT NULL, organisation_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_0152d0a550f838cfa1eedb75de43d2f8_idx (rev), PRIMARY KEY(model_region_project_id, organisation_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_model_region_project_solutions_audit (model_region_project_id INT NOT NULL, solution_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_d1b218f5f85868266d476a4a99472a5e_idx (rev), PRIMARY KEY(model_region_project_id, solution_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_authority_bureau_audit (service_id INT NOT NULL, bureau_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_ef3d584c83dd7462c6a7dfe7c28c8e1e_idx (rev), PRIMARY KEY(service_id, bureau_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_authority_ministry_state_audit (service_id INT NOT NULL, ministry_state_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_8e5be28e58258f591488c80cbeee84c8_idx (rev), PRIMARY KEY(service_id, ministry_state_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_commune_type_audit (service_id INT NOT NULL, commune_type_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_e29b911b5a8c43b5cdbe5aa7fa12d344_idx (rev), PRIMARY KEY(service_id, commune_type_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_jurisdiction_audit (service_id INT NOT NULL, jurisdiction_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_75bee9b2d31620d0fb3b3622896acf76_idx (rev), PRIMARY KEY(service_id, jurisdiction_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_ministry_state_audit (service_id INT NOT NULL, ministry_state_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_1dfa6fbc18f16afd67362402f0618303_idx (rev), PRIMARY KEY(service_id, ministry_state_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_rule_authority_audit (service_id INT NOT NULL, jurisdiction_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_d828e2637ae2570b68ce5644ae6e964b_idx (rev), PRIMARY KEY(service_id, jurisdiction_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_specialized_procedures_audit (service_id INT NOT NULL, specialized_procedure_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_5c993d7969df4e7c7661174945ea70db_idx (rev), PRIMARY KEY(service_id, specialized_procedure_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_system_authority_bureau_audit (service_system_id INT NOT NULL, bureau_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_f0bd8822d3237f49bf69e59d1fae81f8_idx (rev), PRIMARY KEY(service_system_id, bureau_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_system_authority_ministry_state_audit (service_system_id INT NOT NULL, ministry_state_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_cb85476b21e4946920166b5ebf33e961_idx (rev), PRIMARY KEY(service_system_id, ministry_state_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_system_commune_type_audit (service_system_id INT NOT NULL, commune_type_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_56df2e1cd936893814ad2a93683ccd74_idx (rev), PRIMARY KEY(service_system_id, commune_type_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_system_jurisdiction_audit (service_system_id INT NOT NULL, jurisdiction_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_f0a4a435fb7c26cf34138b7c7ff40b15_idx (rev), PRIMARY KEY(service_system_id, jurisdiction_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_system_rule_authority_audit (service_system_id INT NOT NULL, jurisdiction_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_13d9eb9ac16905710c72707c9d93e216_idx (rev), PRIMARY KEY(service_system_id, jurisdiction_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_service_system_solution_audit (service_system_id INT NOT NULL, solution_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_c98457e67c47a3aaf4b62fd17855788c_idx (rev), PRIMARY KEY(service_system_id, solution_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_services_portals_audit (service_id INT NOT NULL, portal_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_cfe1053505343fcc7b5e3cf862a4c2b8_idx (rev), PRIMARY KEY(service_id, portal_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_solution_analog_service_audit (solution_id INT NOT NULL, analog_service_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_24e764327fb65a7fa90556ccb2070584_idx (rev), PRIMARY KEY(solution_id, analog_service_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_solution_contact_audit (solution_id INT NOT NULL, contact_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_9f75b7211ab370f972bea9c201c0a352_idx (rev), PRIMARY KEY(solution_id, contact_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_solution_open_data_audit (solution_id INT NOT NULL, open_data_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_37c0f0352953d6623eb114ed36e68ddc_idx (rev), PRIMARY KEY(solution_id, open_data_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_solution_service_provider_audit (solution_id INT NOT NULL, service_provider_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_6498c1e9b93da0f33e0cee19aef9537b_idx (rev), PRIMARY KEY(solution_id, service_provider_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_solutions_authentications_audit (solution_id INT NOT NULL, authentication_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_6be4700ea991469ad93fcd2948e6ea43_idx (rev), PRIMARY KEY(solution_id, authentication_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_solutions_portals_audit (solution_id INT NOT NULL, portal_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_a5b340d405a5e3c4f14e01e2b393231a_idx (rev), PRIMARY KEY(solution_id, portal_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_solutions_specialized_procedures_audit (solution_id INT NOT NULL, specialized_procedure_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_5e884e9445beb5e0acbe7c9db625c04c_idx (rev), PRIMARY KEY(solution_id, specialized_procedure_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_commune_audit (specialized_procedure_id INT NOT NULL, commune_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_75fae42e0261ebd46f4277b77a5fbb08_idx (rev), PRIMARY KEY(specialized_procedure_id, commune_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ozg_specialized_procedure_service_provider_audit (specialized_procedure_id INT NOT NULL, service_provider_id INT NOT NULL, rev INT NOT NULL, revtype VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rev_829f7b8e1bb659f1b26060d411e90dce_idx (rev), PRIMARY KEY(specialized_procedure_id, service_provider_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE ozg_application_accessibility_document ADD CONSTRAINT FK_D47F606A3E030ACD FOREIGN KEY (application_id) REFERENCES ozg_application (id)');
        $this->addSql('ALTER TABLE ozg_application_accessibility_test_organisations ADD CONSTRAINT FK_1EEFD72B3E030ACD FOREIGN KEY (application_id) REFERENCES ozg_application (id)');
        $this->addSql('ALTER TABLE ozg_application_accessibility_test_organisations ADD CONSTRAINT FK_1EEFD72B9E6B1585 FOREIGN KEY (organisation_id) REFERENCES ozg_organisation (id)');
        $this->addSql('ALTER TABLE ozg_application_audit ADD CONSTRAINT rev_f7eb9ff59e5b71af68e01e6a4ece0136_fk FOREIGN KEY (rev) REFERENCES revisions (id)');
        $this->addSql('ALTER TABLE ozg_application_business_premises ADD CONSTRAINT FK_21854A6C3E030ACD FOREIGN KEY (application_id) REFERENCES ozg_application (id)');
        $this->addSql('ALTER TABLE ozg_application_business_premises ADD CONSTRAINT FK_21854A6C9E6B1585 FOREIGN KEY (organisation_id) REFERENCES ozg_organisation (id)');
        $this->addSql('ALTER TABLE ozg_application_category ADD CONSTRAINT FK_1116C425727ACA70 FOREIGN KEY (parent_id) REFERENCES ozg_application_category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ozg_application_category_mm ADD CONSTRAINT FK_1E359B9112469DE2 FOREIGN KEY (category_id) REFERENCES ozg_application_category (id)');
        $this->addSql('ALTER TABLE ozg_application_category_mm ADD CONSTRAINT FK_1E359B913E030ACD FOREIGN KEY (application_id) REFERENCES ozg_application (id)');
        $this->addSql('ALTER TABLE ozg_application_commune ADD CONSTRAINT FK_F817670131A4F72 FOREIGN KEY (commune_id) REFERENCES ozg_commune (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ozg_application_commune ADD CONSTRAINT FK_F8176703E030ACD FOREIGN KEY (application_id) REFERENCES ozg_application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ozg_application_interface ADD CONSTRAINT FK_938490613E030ACD FOREIGN KEY (application_id) REFERENCES ozg_application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ozg_application_interface_specialized_procedures ADD CONSTRAINT FK_976F13CF452D2882 FOREIGN KEY (specialized_procedure_id) REFERENCES ozg_specialized_procedure (id)');
        $this->addSql('ALTER TABLE ozg_application_interface_specialized_procedures ADD CONSTRAINT FK_976F13CF81E22DB FOREIGN KEY (application_interface_id) REFERENCES ozg_application_interface (id)');
        $this->addSql('ALTER TABLE ozg_application_manufacturer ADD CONSTRAINT FK_22C1A6C93E030ACD FOREIGN KEY (application_id) REFERENCES ozg_application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ozg_application_manufacturer ADD CONSTRAINT FK_22C1A6C9A23B42D FOREIGN KEY (manufacturer_id) REFERENCES ozg_manufacturer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ozg_application_module ADD CONSTRAINT FK_D70098A83E030ACD FOREIGN KEY (application_id) REFERENCES ozg_application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ozg_application_service_provider ADD CONSTRAINT FK_D9E901BC3E030ACD FOREIGN KEY (application_id) REFERENCES ozg_application (id)');
        $this->addSql('ALTER TABLE ozg_application_service_provider ADD CONSTRAINT FK_D9E901BCC6C98E06 FOREIGN KEY (service_provider_id) REFERENCES ozg_service_provider (id)');
        $this->addSql('DROP TABLE IF EXISTS ozg_meta_service_specialized_procedure');
        $this->addSql('DROP TABLE IF EXISTS ozg_specialized_procedure_category_mm');
        $this->addSql('DROP TABLE IF EXISTS ozg_specialized_procedure_business_premises');
        $this->addSql('DROP TABLE IF EXISTS ozg_specialized_procedure_accessibility_test_organisations');
        $this->addSql('DROP TABLE IF EXISTS ozg_specialized_procedure_accessibility_document');
        $this->addSql('DROP TABLE IF EXISTS ozg_specialized_procedure_category');
        $this->addSql('DROP TABLE IF EXISTS ozg_specialized_procedure_interface');
        $this->addSql('DROP TABLE IF EXISTS ozg_specialized_procedure_interface_connected');
        $this->addSql('DROP TABLE IF EXISTS ozg_specialized_procedure_module');
        $this->addSql('ALTER TABLE ozg_specialized_procedure DROP accessibility_test_conducted, DROP privacy, DROP archive, DROP in_house_development, DROP accessibility_test_organisation_others, DROP accessibility_self_testing, DROP accessibility_test_result_type, DROP street, DROP zip_code, DROP town, DROP url');
        $this->addSql('ALTER TABLE ozg_specialized_procedure_audit DROP accessibility_test_conducted, DROP privacy, DROP archive, DROP in_house_development, DROP accessibility_test_organisation_others, DROP accessibility_self_testing, DROP accessibility_test_result_type, DROP street, DROP zip_code, DROP town, DROP url');
        $this->addSql('ALTER TABLE ozg_meta_service_specialized_procedure DROP FOREIGN KEY FK_EEC9C7341C0BE183');
        $this->addSql('DROP INDEX IDX_EEC9C7341C0BE183 ON ozg_meta_service_specialized_procedure');
        $this->addSql('ALTER TABLE ozg_meta_service_specialized_procedure DROP solution_id');
    }
}
