index:
    path: /
    #controller: App\Controller\DefaultController::indexAction
    controller: App\Controller\DashboardController::indexAction

app_search_list:
    path: /admin/saved-search
    controller: App\Controller\SearchController::indexAction

app_search_edit:
    path: /admin/saved-search/edit/{id}
    controller: App\Controller\SearchController::editAction

app_search_save:
    path: /admin/saved-search/save/{id}
    controller: App\Controller\SearchController::saveAction
    defaults:
        id: null

app_frontend_global_search:
    path: /search
    controller: App\Action\SearchAction

app_search_delete:
    path: /admin/saved-search/delete/{id}
    controller: App\Controller\SearchController::deleteAction

app_statistics_chart:
    path: /statistics/chart/{key}
    controller: App\Controller\StatisticsController::chartAction

app_service_choices:
    path: /service/choices
    controller: App\Controller\ServiceController::getChoicesAction
    methods: [POST]

app_record_export:
    path: /record-export/{recordType}/{recordId}/{property}
    controller: App\Controller\ExportController::exportAction

authentication_token:
    path: /api/authentication_token
    methods: ['POST']