index:
    path: /
    #controller: App\Controller\DefaultController::indexAction
    controller: App\Controller\DashboardController::indexAction

app_statistics_chart:
    path: /statistics/chart/{key}
    controller: App\Controller\StatisticsController::chartAction

app_service_choices:
    path: /service/choices
    controller: App\Controller\ServiceController::getChoicesAction
    methods: [POST]

app_record_export:
    path: /record-export/{recordType}/{recordId}/{property}
    controller: App\Controller\ExportController::exportAction

authentication_token:
    path: /api/authentication_token
    methods: ['POST']

simple_things_entity_audit:
    resource: "@SimpleThingsEntityAuditBundle/Resources/config/routing.yml"
    prefix: /audit