index:
    path: /
    controller: App\Controller\DefaultController::indexAction

app_search_list:
    path: /search
    controller: App\Controller\SearchController::indexAction

app_search_edit:
    path: /search/edit/{id}
    controller: App\Controller\SearchController::editAction

app_search_save:
    path: /search/save/{id}
    controller: App\Controller\SearchController::saveAction
    defaults:
        id: null

app_search_delete:
    path: /search/delete/{id}
    controller: App\Controller\SearchController::deleteAction

frontend_app_service_list:
    path: /leistungen
    controller: App\Controller\ServiceController::listAction

frontend_app_service_show:
    path: /leistungen/{id}/show
    controller: App\Controller\ServiceController::showAction

frontend_app_service_export:
    path: /leistungen/export
    controller: App\Controller\ServiceController::exportAction

frontend_app_servicesystem_list:
    path: /ozg-leistungen
    controller: App\Controller\ServiceSystemController::listAction

frontend_app_servicesystem_show:
    path: /ozg-leistungen/{id}/show
    controller: App\Controller\ServiceSystemController::showAction

frontend_app_servicesystem_export:
    path: /ozg-leistungen/export
    controller: App\Controller\ServiceSystemController::exportAction

frontend_app_implementationproject_list:
    path: /umsetzungsprojekte
    controller: App\Controller\ImplementationProjectController::listAction

frontend_app_implementationproject_show:
    path: /umsetzungsprojekte/{id}/show
    controller: App\Controller\ImplementationProjectController::showAction

frontend_app_implementationproject_export:
    path: /umsetzungsprojekte/export
    controller: App\Controller\ImplementationProjectController::exportAction

frontend_app_solution_list:
    path: /loesungen
    controller: App\Controller\SolutionController::listAction

frontend_app_solution_show:
    path: /loesungen/{id}/show
    controller: App\Controller\SolutionController::showAction

frontend_app_solution_export:
    path: /loesungen/export
    controller: App\Controller\SolutionController::exportAction