# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: 'de'
  locales: ['de']

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']


  App\Translator\PrefixedUnderscoreLabelTranslatorStrategy:
    public: true

  App\Admin\AuthenticationAdmin:
    arguments:
      - ~
      - App\Entity\Authentication
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.authentication.authentication_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\CommuneAdmin:
    arguments:
      - ~
      - App\Entity\Commune
      - ~
    calls:
      - [addChild, ['@App\Admin\SolutionAdmin', 'communes']]
      - [addChild, ['@App\Admin\OfficeAdmin', 'commune']]
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.commune.commune_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\FormServerAdmin:
    arguments:
      - ~
      - App\Entity\FormServer
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.form_server.form_server_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\ImplementationStatusAdmin:
    arguments:
      - ~
      - App\Entity\ImplementationStatus
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.implementation_status.implementation_status_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\ImplementationProjectAdmin:
    arguments:
      - ~
      - App\Entity\ImplementationProject
      - ~
    calls:
      - [setTemplate, ['show', 'ImplementationProjectAdmin/show.html.twig']]
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.implementation_project.implementation_project_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\Frontend\ImplementationProjectAdmin:
    arguments:
      - ~
      - App\Entity\ImplementationProject
      - ~
    calls:
      - [setTemplate, ['show', 'ImplementationProjectAdmin/show.html.twig']]
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.implementation_project.implementation_project_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
        datagrid_builder: 'App\Builder\CustomDatagridBuilder'
    public: true

  App\Admin\JurisdictionAdmin:
    arguments:
      - ~
      - App\Entity\Jurisdiction
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.jurisdiction.jurisdiction_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\LaboratoryAdmin:
    arguments:
      - ~
      - App\Entity\Laboratory
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.laboratory.laboratory_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\ManufacturerAdmin:
    arguments:
      - ~
      - App\Entity\Manufacturer
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.manufacturer.manufacturer_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\MaturityAdmin:
    arguments:
      - ~
      - App\Entity\Maturity
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.maturity.maturity_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\OfficeAdmin:
    arguments:
      - ~
      - App\Entity\Office
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.office.office_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\PaymentTypeAdmin:
    arguments:
      - ~
      - App\Entity\PaymentType
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.payment_type.payment_type_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\PortalAdmin:
    arguments:
      - ~
      - App\Entity\Portal
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.portal.portal_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\PriorityAdmin:
    arguments:
      - ~
      - App\Entity\Priority
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.priority.priority_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\SituationAdmin:
    arguments:
      - ~
      - App\Entity\Situation
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.situation.situation_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\ServiceSystemAdmin:
    arguments:
      - ~
      - App\Entity\ServiceSystem
      - ~
    calls:
      - [setTemplate, ['show', 'ServiceSystemAdmin/show.html.twig']]
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.service_system.service_system_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\ServiceAdmin:
    arguments:
      - ~
      - App\Entity\Service
      - ~
    calls:
      - [setTemplate, ['show', 'ServiceAdmin/show.html.twig']]
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.service.service_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\Frontend\ServiceAdmin:
    arguments:
      - ~
      - App\Entity\Service
      - ~
    calls:
      - [setTemplate, ['show', 'ServiceAdmin/show.html.twig']]
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.service.service_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
        datagrid_builder: 'App\Builder\CustomDatagridBuilder'
    public: true

  App\Admin\ServiceProviderAdmin:
    arguments:
      - ~
      - App\Entity\ServiceProvider
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.service_provider.service_provider_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\ServiceSolutionAdmin:
    arguments:
      - ~
      - App\Entity\ServiceSolution
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.service_solution.service_solution_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\StatusAdmin:
    arguments:
      - ~
      - App\Entity\Status
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.status.status_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\SpecializedProcedureAdmin:
    arguments:
      - ~
      - App\Entity\SpecializedProcedure
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.specialized_procedure.specialized_procedure_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Admin\SolutionAdmin:
    arguments:
      - ~
      - App\Entity\Solution
      - ~
    calls:
      - [addChild, ['@App\Admin\ServiceSolutionAdmin', 'solution']]
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.solution.solution_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Entity\SolutionManager:
    arguments:
      - '@doctrine'

  App\Admin\SubjectAdmin:
    arguments:
      - ~
      - App\Entity\Subject
      - ~
    tags:
      - name:         sonata.admin
        manager_type: orm
        label:        app.subject.subject_list
        label_translator_strategy: 'App\Translator\PrefixedUnderscoreLabelTranslatorStrategy'
    public: true

  App\Block\RecentSolutionsBlock:
    arguments:
      - '@sonata.templating'
      - '@App\Entity\SolutionManager'
      - '@?sonata.admin.pool'
    tags:
      - { name: sonata.block }

  App\Security\Authorization\Voter\ProtectSuperAdminVoter:
    arguments:
      - '@security.authorization_checker'
    tags:
      - { name: security.voter }

  App\Form\Type\SecurityRolesType:
    arguments:
      - '@kernel'
    tags:
      - { name: form.type }

  App\Builder\CustomDatagridBuilder:
    arguments:
      - '@form.factory'
      - '@sonata.admin.builder.filter.factory'
      - '@sonata.admin.guesser.orm_datagrid_chain'
      - '%form.type_extension.csrf.enabled%'

  App\EventListener\MenuBuilderListener:
    arguments:
      - '@request_stack'
    tags:
      - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

  App\Controller\SearchController:
    arguments:
      - '@sonata.admin.pool'
      - '@translator'
